SECTION "Charmap",ROM0 
; Charmap definition (based on the hello_world.png image, and looking in the VRAM viewer after loading it in BGB helps finding the values for each character)
CHARMAP "A",$14
CHARMAP "B",$15
CHARMAP "C",$16
CHARMAP "D",$17
CHARMAP "E",$18
CHARMAP "F",$19
CHARMAP "G",$1A
CHARMAP "H",$1B
CHARMAP "I",$1C
CHARMAP "J",$1D
CHARMAP "K",$1E
CHARMAP "L",$1F
CHARMAP "M",$20
CHARMAP "N",$21
CHARMAP "O",$22
CHARMAP "P",$23
CHARMAP "Q",$24
CHARMAP "R",$25
CHARMAP "S",$26
CHARMAP "T",$27
CHARMAP "U",$28
CHARMAP "V",$29
CHARMAP "W",$2A
CHARMAP "X",$2B
CHARMAP "Y",$2C
CHARMAP "Z",$2D
CHARMAP "<happy>",$02
CHARMAP "<sad>",$03
CHARMAP "<heart>",$04
CHARMAP "<up>",$07
CHARMAP "<down>",$08
CHARMAP "<left>",$06
CHARMAP "<right>",$05
CHARMAP " ",$00
CHARMAP "<end>",$30 ; Choose some non-character tile that's easy to remember 