SCREEN_WIDTH  EQU 20
SCREEN_HEIGHT EQU 18
CANVAS_WIDTH  EQU 12
FULL_WIDTH    EQU $1F

    const_def
    const MENU_TITLE_ANIM ; 0
    const MENU_TITLE ; 1
    const MENU_LEVEL_SELECT ; 2
    const MENU_GAME_OVER ; 3

MARGIN_RIGHT EQU 160 - 24
MARGIN_LEFT EQU 2 * 8
MARGIN_TOP EQU 6 * 8
MARGIN_BOT EQU 144 - 24

MOVE_TILE_X  EQU 24
MOVE_TILE_Y  EQU 16
MOVE_SPEED_X EQU 2
MOVE_SPEED_Y EQU 2

; ATTRIBUTES
SPRITE_PRIORITY = 1 << 7
SPRITE_FLIPY    = 1 << 6
SPRITE_FLIPX    = 1 << 5
SPRITE_PAL      = 1 << 4

SOUND_1 EQU 1

; SPRITE VARIABLE CONSTANTS
    const_def
    const SPR_PROPERTIES   ; 0
    const SPR_VAR1         ; 1
    const SPR_VAR2         ; 2
    const SPR_VAR3         ; 3
    const SPR_ANIM_DUR     ; 4
    const SPR_ANIM_FRAME   ; 5
    const SPR_ANIM_FRAMES  ; 6
    const SPR_ANIM_CHANGED ; 7

; SPRITE PROPERTIES
; SPRITE TYPE CONSTANTS
    const_def
    const PLAYER
    const ENEMY 
    const BULLET
    const TYPE_3
    const TYPE_4
TYPE_MASK EQU %1111

; SPRITE SIZE CONSTANTS
SIZE_MASK   EQU %110000
SIZE_SMALL  EQU %00
SIZE_MEDIUM EQU %01
SIZE_BIG    EQU %10
MAX_SIZE    EQU 3

; ANIMATION CONSTANTS (used in data/animations.asm)
    const_def
    const ANIM_MOVE_DOWN
    const ANIM_MOVE_UP
    const ANIM_MOVE_RIGHT
    const ANIM_MOVE_LEFT

; STAGE CONSTANTS
    const_def 0, 24
    const LANEX1
    const LANEX2
    const LANEX3
    const LANEX4
    const LANEX5